apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-ordnungsamt
  name: ms-ordnungsamt
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-ordnungsamt
    spec:
      containers:
      - image: ms-ordnungsamt-frontend
        name: ms-ordnungsamt-frontend
        ports:
        - containerPort: 80
      - image: ms-ordnungsamt-backend
        name: ms-ordnungsamt-backend
        ports:
        - containerPort: 8080
      - image: mongo
        name: ms-ordnungsamt-db
        volumeMounts:
          - mountPath: /data/db
            name: db
      restartPolicy: Always
      volumes:
        - name: db
          gcePersistentDisk:
            pdName: ms-ordnungsamt
            fsType: ext4
status: {}
