apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-ordnungsamt
  name: ms-ordnungsamt
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: ms-ordnungsamt
status:
  loadBalancer: {}
